resources:
  - name: koans
    type: git
    source:
      uri: https://github.com/jtxyz/factor-koans.git
      branch: master

jobs:
  - name: test-koans
    plan:
      - get: koans
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jtxyz/ruby-factor
              tag: 'latest'

          inputs:
          - name: koans

          run:
            path: bash
            args:
              - -c
              - cd koans && ./koans_spec.rb
